### ISSUE TITLE
About computational resources

### ISSUE THREAD

**Issue by abcdvzz** [CurryYuan/X-Trans2Cap#2]
Hi Zhihao,

I wanna follow your work but I am not sure if my computation resources could support this task. In your paper, you said the experiments are conducted on RTX2080Ti GPUs. Could you please tell me more about it? How many GPUs, how much CPU memory do I need and what's the size of the dataset? Thank you very much.

Best,
xxx

**Comment by CurryYuan** [comment]
Single RTX2080Ti GPU is ok.

**Comment by abcdvzz** [comment]
> Single RTX2080Ti GPU is ok.

Thank you for your kind reply. Could you pls tell me when will you release the rest of your code?
