### ISSUE TITLE
ScanNet dataset format for training the model

### ISSUE THREAD

**Issue by EnnaSachdeva** [CurryYuan/X-Trans2Cap#9]
Hi,

The training code seems to use these files for each of the ScanNet scenarios- "aligned_vert.npy, ins_label.npy, sem_label.npy, aligned_bbox.npy". But these files are missing from the repo. How is the original ScanNet data transformed into this format? Can you please share that codebase, or share the transformed data in the above format?

Thanks!!

**Comment by CurryYuan** [comment]
Hi, @EnnaSachdeva , please refer to [Scan2Cap](https://github.com/daveredrum/Scan2Cap) for data preparation.

**Comment by 1301358882** [comment]
> Hi,
> 
> The training code seems to use these files for each of the ScanNet scenarios- "aligned_vert.npy, ins_label.npy, sem_label.npy, aligned_bbox.npy". But these files are missing from the repo. How is the original ScanNet data transformed into this format? Can you please share that codebase, or share the transformed data in the above format?
> 
> Thanks!!

Hi, have you solved it yet? How was it resolved?

**Comment by CurryYuan** [comment]
@1301358882 , I believe you can find what you need [here](https://github.com/daveredrum/Scan2Cap?tab=readme-ov-file#data-preparation).
